added dall.e.2.0
JasonDsouza212/free-hit pull request #476
Opened 2023-06-04 16:18 UTC by AmanSingh6574

Issue #475

2023-06-04 16:23 UTC, JasonDsouza212 commented
The JS syntax is wrong , look into it and also add the tool at the last of the DB

2023-06-04 16:23 UTC, AmanSingh6574 commented
@JasonDsouza212 sir why there is this deployment error ?

2023-06-04 16:54 UTC, AmanSingh6574 commented
> The JS syntax is wrong , look into it and also add the tool at the last of the DB

sir not understood what exactly is wrong is it the description length? 10-12 words or something

2023-06-04 17:51 UTC, shyamtawli requested changes

2023-06-04 17:51 UTC, shyamtawli commented on src/DB/product.json
> +
```suggestion
},
```

2023-06-07 04:33 UTC, AmanSingh6574 commented
@JasonDsouza212 sir i have made the changes

2023-06-08 12:56 UTC, merged